#!/usr/bin/env python3
"""Reproducible six-scene motion packages for the audited LinkedIn schedule.

No platform calls or credentials. Reuses the Shabina V2 typography/palette;
all geometry is drawn from code, not generated by an image or language API.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import html
import json
import math
import subprocess
from functools import lru_cache
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output/linkedin/scheduled-motion-2026-09-05"
W, H, FPS, SECONDS = 1080, 1350, 24, 36
INK, BLUE, WHITE, PALE, LINE = "#071426", "#075BDA", "#FFFFFF", "#EFF5FF", "#BDD3F0"
SECTIONS = ["BOUNDARY", "ARCHITECTURE", "EVIDENCE", "CONTRACT", "FAILURE", "DECISION"]
OVERFLOWS: set[str] = set()


@lru_cache(maxsize=64)
def font(size, bold=False, mono=False):
    path = "/System/Library/Fonts/SFNSMono.ttf" if mono else "/System/Library/Fonts/Supplemental/Arial" + (" Bold" if bold else "") + ".ttf"
    return ImageFont.truetype(path, size)


@lru_cache(maxsize=8192)
def wrap(value, size, width, bold=False, mono=False):
    lines, current = [], ""
    for word in str(value).split():
        candidate = (current + " " + word).strip()
        if font(size, bold, mono).getlength(candidate) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def text(d, x, y, value, size=28, color=INK, bold=False, width=960, max_lines=8, mono=False):
    lines = wrap(value, size, width, bold, mono)
    if len(lines) > max_lines:
        OVERFLOWS.add(f"lines>{max_lines}: {value}")
    for i, line in enumerate(lines):
        if x + font(size, bold, mono).getlength(line) > W - 30 or y + i * size * 1.24 + size > H - 20:
            OVERFLOWS.add(f"canvas overflow: {value}")
        d.text((x, y + i * size * 1.24), line, font=font(size, bold, mono), fill=color)
    return y + len(lines) * size * 1.24


def center(d, x, y, value, size=26, color=INK, bold=False):
    d.text((x, y), str(value), font=font(size, bold), fill=color, anchor="mm")


def smooth(p):
    p = max(0., min(1., p))
    return p * p * (3 - 2 * p)


def box(d, coords, fill=WHITE, outline=LINE, width=2):
    d.rounded_rectangle(coords, radius=20, fill=fill, outline=outline, width=width)


def arrow(d, a, b, t, dashed=False):
    if dashed:
        for i in range(0, 20, 2):
            u, v = i / 20, (i + 1) / 20
            d.line((a[0] + (b[0]-a[0])*u, a[1] + (b[1]-a[1])*u,
                    a[0] + (b[0]-a[0])*v, a[1] + (b[1]-a[1])*v), fill=INK, width=3)
    else:
        d.line((*a, *b), fill=BLUE, width=3)
    angle = math.atan2(b[1] - a[1], b[0] - a[0])
    d.polygon([b, (b[0]-12*math.cos(angle-.5), b[1]-12*math.sin(angle-.5)),
               (b[0]-12*math.cos(angle+.5), b[1]-12*math.sin(angle+.5))], fill=INK if dashed else BLUE)
    p = t % 1
    x, y = a[0] + (b[0]-a[0])*p, a[1] + (b[1]-a[1])*p
    d.ellipse((x-7,y-7,x+7,y+7), fill=BLUE)


def source_posts():
    tree = ast.parse((ROOT / "scripts/build_linkedin_carousels.py").read_text())
    return next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "POSTS" for t in n.targets))


EARLY = [
    dict(id="S01",slug="sop-execution",short="SOP EXECUTION",schedule="2026-09-07T08:45:00+05:30",media="text only",title="A perfect answer can hide a wrong action",subtitle="A correction must change state, confirmation and the resulting write.",metric="5/5 vs 1/5",metric_label="Language quality versus operational safety in the scheduled example",flow=["Input", "Correct", "Version", "Confirm", "Write", "Verify"],lanes=[("STATE",["Observation","Correction","Supersession"]),("CONTROL",["SOP contract","Confirmation","Tool order"]),("EVIDENCE",["Trace","Postcondition","Owner"])],principle="Evaluate the state transition, not just the conversation.",score_rows=[("Quality score","5 / 5","EXAMPLE"),("Safety score","1 / 5","EXAMPLE"),("SOP contracts","~15","MODEL")],decision_rule="Invalidate the previous value, reconfirm the correction, then verify the write.",chart=[("Language quality",5),("Operational safety",1)],unit="score / 5",domain=5,formula="safe_write = current_version AND confirmed_delta AND valid_policy",contract=["action: apply_correction","supersedes: observation_v1","new_value: 1000 mg [example]","confirmation: exact_new_value","precondition: current_version","postcondition: observed_write"],failure=["Correction arrives after confirmation","Invalidate v1 and its old approval","Reconfirm v2 before any write"],question="Does your evaluation prove that corrections supersede prior state?",note="Illustrated failure case from scheduled copy; not clinical guidance.",chart_title="Two evaluation dimensions",chart_note="Attributed example in scheduled post; scores are not production measurements."),
    dict(id="S02",slug="account-escalation",short="CRM AUTHORITY",schedule="2026-09-09T14:00:00+05:30",media="Medium link preview",title="Evidence is not permission to execute",subtitle="The account is worth $2.4M. Authority belongs to the exact action.",metric="$2.4M",metric_label="Illustrative account value, not the loss of every candidate action",flow=["Signals","Evidence","Risk","Approve","Lease","Verify"],lanes=[("PREPARE",["Support","Contract","Quote"]),("DECIDE",["Expected loss","Policy","Human gate"]),("COMMIT",["Bound lease","CRM version","Verifier"])],principle="A recommendation can be correct and still lack authority.",score_rows=[("Account value","$2.4M","SCENARIO"),("Control stages","6","CONTRACT"),("Lease scope","1 action","BOUND")],decision_rule="Release the exact approved delta only after the evidence, risk and policy gates pass.",chart=[("Requested 12% delta",288000),("Approved 8% example",192000)],unit="USD on $2.4M renewal",domain=320000,formula="action_gate = evidence AND policy AND required_approval",contract=["resource: one_named_quote","delta: exact_approved_change","evidence_hash: current_pack","policy_epoch: current","use_limit: 1","recovery: declared_before_act"],failure=["Quote changes after human approval","Reject the stale resource version","Reassess evidence and request a new lease"],question="Where does recommendation become a contractual commitment?",note="Conceptual CRM workflow; values are illustrative, not an actual customer account.",chart_title="Commercial delta by scenario",chart_note="Source-story illustration: request and approval example are distinct cases."),
    dict(id="S03",slug="model-serving-boundary",short="MODEL SERVING",schedule="2026-09-11T08:45:00+05:30",media="text only",title="Separate selection from execution routing",subtitle="Keep a stable client contract while routing moves closer to the workload.",metric="5 capabilities",metric_label="Interface, routing, safe rollout, isolation and outcome observability",flow=["Client","Contract","Select","Route","Model","Observe"],lanes=[("CONTROL",["Model catalog","Selection","Release policy"]),("DATA",["Stable API","Local router","Serving pool"]),("ASSURE",["Shadow","Canary","Rollback"])],principle="A model change should not force every client to change.",score_rows=[("Interface","Stable","CONTRACT"),("Rollout","Canary","CONTROL"),("Rollback","Measured","SLO")],decision_rule="Move the routing decision near the data plane while preserving a versioned client interface.",chart=None,formula="route = eligible(model, policy, context, deadline)",contract=["client_contract: versioned","model_selection: control_plane","routing: near_data_plane","isolation: workload_boundary","rollout: shadow_then_canary","rollback: known_good_version"],failure=["A canary violates its declared SLO","Route traffic to the known-good version","Isolate the failing serving pool"],question="Which shared dependency expands your platform's blast radius?",note="Conceptual architecture inspired by the scheduled post; no new Netflix claims.",chart_title="Release controls before scale",chart_note="Architecture comparison, not a revalidation of third-party performance claims."),
    dict(id="S04",slug="attention-runway",short="ATTENTION RUNWAY",schedule="2026-09-16T08:45:00+05:30",media="text only",title="Engineering attention is not free",subtitle="Repeated reporting competes with product-building capacity.",metric="$1.8M / year",metric_label="Opportunity cost in the scheduled thought experiment, not cash savings",flow=["Question","Definition","Source","Reconcile","Answer","Decide"],lanes=[("DEMAND",["Executive question","Metric owner","Priority"]),("TRUST",["CRM + finance","Shared definition","Reconcile"]),("CAPACITY",["Self-service","Product time","Decision review"])],principle="Measure capacity returned to product work, not automation count.",score_rows=[("Engineers","80","ASSUMED"),("Annual cost each","$180K","ASSUMED"),("Reporting share","12.5%","ASSUMED")],decision_rule="Treat recurring data requests as an owned service with a trusted-answer objective.",chart=[("Product / other capacity",12600000),("Repeated reporting",1800000)],unit="USD / year, capacity cost",domain=14400000,formula="80 x $180,000 x (1/8) = $1,800,000 / year",contract=["metric: one_owned_definition","source_versions: explicit","freshness: business_relevant","answer_owner: accountable","decision_time: measured","capacity_returned: tracked"],failure=["CRM and finance disagree on a metric","Preserve both definitions and owners","Resolve before issuing a trusted answer"],question="What share of engineering capacity actually builds the product?",note="Thought experiment from scheduled copy; opportunity cost is not realized savings.",chart_title="Annual engineering capacity cost",chart_note="80 engineers × $180,000/year; one-eighth assigned to repeated reporting."),
]

# Topic-specific motion semantics. Existing campaign facts are imported above;
# these additions are conceptual contracts, not runnable production code.
EXTRAS = [
 ("2026-09-18T08:45:00+05:30",[("Standing-role reach",100),("Constrained lease",.35)],"% modeled reachable authority",100,"allow = signature AND scope AND expiry AND unused",
  ["resource: quote/771","delta: discount 0% -> 8%","ttl: 90 seconds","use_limit: 1","expected_version: bound","verifier: independent"],
  ["Replay of an already consumed lease","Reject at the effect gateway","Record denial; do not repeat the mutation"],"Which standing role can become one-use authority?"),
 ("2026-09-21T14:00:00+05:30",[("Arrival rate",42),("Review capacity",50),("Overload example",52)],"decisions / hour",60,"rho = lambda / (c x mu); stability requires rho < 1",
  ["reviewers: 5 qualified","mean_service: 6 minutes","capacity: 50 decisions/hour","arrival_example: 42/hour","deadline: action_specific","on_expiry: no_authority"],
  ["52 arrivals/hour exceed 50/hour capacity","Apply a declared overload / expiry policy","Never turn timeout into automatic approval"],"Do you measure risk-weighted waiting time?"),
 ("2026-09-23T08:45:00+05:30",[("Ambiguity objective",15),("Illustrative p99",31)],"minutes; ambiguity age",35,"seal = observed_effect AND valid_authority AND lineage",
  ["action_id: stable_across_retry","intent_hash: bound","approval_hash: bound","authority_jti: bound","effect: independently_observed","recovery_state: explicit"],
  ["Request times out after possible commit","Mark AMBIGUOUS; retain the action ID","Reconcile external truth before retry"],"Can a receipt prove the effect without six-system reconstruction?"),
 ("2026-09-25T14:00:00+05:30",[("Ambiguity objective",10),("Illustrative p99",24)],"minutes; ambiguity age",30,"commit = current_epoch AND unique_action AND causal_version",
  ["workflow_id: durable","owner_epoch: monotonic","action_key: stable","causal_version: checked","postcondition: verified","saga_owner: assigned"],
  ["A disconnected owner returns with stale work","Fence the old epoch at commit","The current owner reconciles the workflow"],"Which invariant fails first: ownership, uniqueness or recovery?"),
 ("2026-09-28T08:45:00+05:30",[("Model I/O",.049),("Tools",.047),("Verification",.039),("Retries",.025),("Delay / recovery / route",.026)],"USD / completed workflow",.05,"choose r in feasible_routes; minimize cost + delay + risk",
  ["route: model+context+tools","privacy: hard_constraint","authority: hard_constraint","quality_floor: task_class","tail_loss: CVaR95","feedback: verified_outcomes"],
  ["Low-cost route violates a quality or policy gate","Remove it from the feasible set","Optimize cost only among eligible routes"],"Does your router price the full verified workflow?"),
 ("2026-09-30T14:00:00+05:30",[("Local-enforcement target",30),("Illustrative enforcement",41)],"seconds; local enforcement",45,"accept_effect = presented_epoch == current_epoch",
  ["containment_epoch: signed","effect_gate: fail_closed","in_flight: 1264 actions","command_p99: 2.1 seconds","stop_budget: 85 seconds","truth: independently_reconciled"],
  ["Worker continues after a containment trigger","New epoch rejects stale effect authority","Inventory and reconcile every in-flight action"],"What proves your emergency stop actually stopped effects?"),
 ("2026-10-02T08:45:00+05:30",[("Point estimate",88/95*100),("95% Wilson lower bound",85.5643147117504),("Required floor",92)],"% verified successes, n=95",100,"promote = cohort_bound >= floor AND recovery_gate",
  ["critical_cohort: 88 / 95","confidence: 95% two_sided","lower_bound: Wilson","production_floor: 92%","zero_failures: not_zero_risk","authority: staged_promotion"],
  ["Point estimate passes; uncertainty bound fails","Hold the current authority stage","Collect representative evidence before promotion"],"Which production claim has the weakest evidence?"),
 ("2026-10-05T14:00:00+05:30",[("Deletion objective",24),("Illustrative deletion p99",31)],"hours; derivative deletion",36,"admit = provenance AND purpose AND freshness AND trust",
  ["assertion: typed_version","valid_time: domain_specific","purpose: authorized","conflicts: preserved","derivatives: reverse_lineage","deletion: completion_receipt"],
  ["Poisoned memory crosses an admission boundary","Narrow the affected read and action classes","Reconcile derivatives before deletion is complete"],"Which memory SLO exposes risk that latency hides?"),
 ("2026-10-07T08:45:00+05:30",[("Requested 12% discount",288000),("Approved 8% example",192000)],"USD on $2.4M renewal",320000,"commit = approved_delta AND expected_quote_version",
  ["renewal: $2.4M","request: 12% = $288K","approval_example: 8%","resource: one_named_quote","expected_version: exact","retry: reconcile_before_act"],
  ["Evidence or quote version changes after approval","Invalidate the old decision and lease","Recompute risk before a commercial commitment"],"Where does your CRM enforce the commitment boundary?"),
 ("2026-10-09T14:00:00+05:30",[("Inference",.198),("Human review",.4125),("Tier-0 control plane",.2375),("Other operating costs",.1022)],"USD / attempted objective",.45,"cost_per_verified = cost_per_attempt / verified_rate",
  ["attempts_per_month: 40000","cost_per_attempt: $0.9502","verified_rate: 0.837","verified_unit_cost: $1.135","review: $0.4125 / attempt","control_plane: $0.2375 / attempt"],
  ["Cheap tokens raise retries and failed verification","Recompute cost per verified outcome","Reject a route whose denominator destroys savings"],"Can your business case price the verified denominator?"),
]


def posts():
    result = [dict(p) for p in EARLY]
    for index, (p, extra) in enumerate(zip(source_posts(), EXTRAS)):
        schedule, chart, unit, domain, formula, contract, failure, question = extra
        p.update(id=f"S{index+5:02d}",schedule=schedule,media="3-page PDF",chart=chart,unit=unit,domain=domain,formula=formula,contract=contract,failure=failure,question=question,
                 chart_title="Operating evidence comparison",chart_note="Synthetic examples from the corresponding approved campaign and source story.",
                 note="Illustrative / synthetic operating model. Not observed production results.")
        if p["id"] == "S11":
            p["chart_title"] = "Critical-cohort evidence and floor"
            p["chart_note"] = "88 successes / 95 independent representative cases; 95% two-sided Wilson interval."
        if p["id"] == "S06":
            p["chart_note"] = "Synthetic M/M/5: Poisson arrivals, exponential six-minute service, five identical servers."
            p["score_rows"] = [("Wait at 42/hour", "4.8 min", "M/M/5"), ("Value of review", "$505", "PER ACTION"), ("Modeled cost minimum", "~60%", "REVIEW RATE")]
        if p["id"] in ("S09", "S14"):
            p["chart_title"] = "Full workflow cost components"
        if p["id"] == "S09":
            p["score_rows"] = [("Workflow total", "$0.186", "MODEL"), ("Model I/O share", "26.3%", "OF TOTAL"), ("ECE calibration", "0.047", "BREACH > .030")]
        result.append(p)
    return result


def base(p, scene, t):
    image = Image.new("RGB", (W,H), WHITE)
    d = ImageDraw.Draw(image)
    text(d,52,34,"PRODUCTION AI / MOTION NOTES",20,BLUE,True)
    text(d,840,34,p["id"]+" · ADITYA",20,BLUE,True,width=190)
    for i,label in enumerate(SECTIONS):
        x = 52 + i*165
        d.line((x,86,x+139,86),fill=BLUE if i<=scene else LINE,width=4)
        text(d,x,101,f"0{i+1} {label}",15,BLUE,i==scene,width=160)
    text(d,52,148,p["short"],21,BLUE,True,width=970)
    d.line((52,1212,1028,1212),fill=LINE,width=2)
    text(d,52,1230,p["note"],20,INK,width=970,max_lines=2)
    text(d,52,1298,"CONCEPTUAL ANIMATION · NO LIVE TELEMETRY",17,BLUE,width=960)
    d.rectangle((0,H-7,int(W*t/SECONDS),H),fill=BLUE)
    return image,d


def heading(d,title,subtitle):
    end=text(d,52,196,title,52,INK,True,width=970,max_lines=2)
    text(d,52,end+15,subtitle,26,width=970,max_lines=2)


def flow_row(d,labels,y,t):
    for i,label in enumerate(labels):
        x=54+i*164
        active=int(t*1.2)%len(labels)==i
        box(d,(x,y,x+145,y+110),PALE if active else WHITE,BLUE if active else LINE,3 if active else 2)
        text(d,x+13,y+21,label,24,BLUE if active else INK,True,width=122,max_lines=2)
        if i<len(labels)-1:
            arrow(d,(x+148,y+55),(x+160,y+55),t*.9-i*.15)


def scene_problem(p,d,t):
    heading(d,p["title"],p["subtitle"])
    box(d,(52,429,1028,676),PALE,BLUE)
    size=72 if len(p["metric"])<19 else 55
    text(d,82,461,p["metric"],size,BLUE,True,width=910,max_lines=1)
    text(d,82,560,p["metric_label"],28,width=900,max_lines=2)
    flow_row(d,p["flow"],744,t)
    text(d,52,927,"THE OPERATING BOUNDARY",22,BLUE,True)
    text(d,52,975,p["principle"],39,INK,True,width=956,max_lines=3)


def scene_arch(p,d,t):
    heading(d,"Make the control path explicit", "Moving markers show the conceptual sequence—not measured throughput.")
    for lane,(label,nodes) in enumerate(p["lanes"]):
        y=415+lane*228
        text(d,54,y,label,22,BLUE,True)
        span=970/len(nodes)
        for i,node in enumerate(nodes):
            x=54+i*span
            active=int(t*1.5)%sum(len(l[1]) for l in p["lanes"])==sum(len(l[1]) for l in p["lanes"][:lane])+i
            box(d,(x,y+45,x+span-24,y+154),PALE if active else WHITE,BLUE if active else LINE,3 if active else 2)
            text(d,x+18,y+68,node,27,BLUE if active else INK,True,width=span-62,max_lines=2)
            if i<len(nodes)-1:arrow(d,(x+span-20,y+100),(x+span-4,y+100),t-lane*.3)
        if lane<2:arrow(d,(540,y+161),(540,y+214),t*.8)
    text(d,54,1112,"No effect should bypass the declared control boundary.",27,BLUE,True,width=950,max_lines=2)


def fmt(value):
    if value>=10000:return f"${value/1000:,.0f}K" if value<1000000 else f"${value/1000000:,.1f}M"
    if value>=1:return f"{value:,.1f}".rstrip("0").rstrip(".")
    return f"{value:.4f}".rstrip("0").rstrip(".")


def scene_evidence(p,d,t):
    heading(d,p["chart_title"],p["chart_note"])
    if not p["chart"]:
        for i,label in enumerate(["Stable client interface","Context-aware local routing","Shadow / canary / rollback","Workload isolation","Outcome-linked observability"]):
            y=423+i*121
            box(d,(54,y,1026,y+93),PALE if int(t)%5==i else WHITE)
            center(d,100,y+45,f"0{i+1}",28,BLUE,True)
            text(d,147,y+28,label,31,INK,True,width=835,max_lines=1)
    else:
        text(d,54,389,p["unit"],24,BLUE,True)
        values=p["chart"]
        rows=len(values)
        step=min(143,570/rows)
        for i,(label,value) in enumerate(values):
            y=454+i*step
            text(d,54,y,label,25,INK,True,width=690,max_lines=1)
            text(d,825,y,fmt(value),26,BLUE,True,width=198,max_lines=1)
            d.rectangle((54,y+48,1026,y+78),fill=PALE)
            end=54+972*value/p["domain"]*smooth((t-.16*i)/1.4)
            if end>54:d.rectangle((54,y+48,end,y+78),fill=BLUE)
        axis_y=454+(rows-1)*step+100
        text(d,54,axis_y,"0",20,INK)
        d.text((1026,axis_y),fmt(p["domain"]),font=font(20),fill=INK,anchor="ra")
        text(d,54,axis_y+38,"Zero baseline · bar lengths reveal the stated values",21,INK,width=950)
        if rows <= 2:
            box(d,(54,axis_y+98,1026,1040),WHITE,LINE)
            text(d,78,axis_y+122,"INTERPRETATION",20,BLUE,True)
            text(d,78,axis_y+161,p["principle"],30,INK,True,width=921,max_lines=3)
    box(d,(54,1080,1026,1170),WHITE,BLUE)
    text(d,74,1100,p["formula"],25,INK,True,width=930,max_lines=2)


def scene_contract(p,d,t):
    heading(d,"Bind the decision to a contract", "Illustrative schema—not executable authorization code.")
    box(d,(54,410,1026,1048),PALE,BLUE)
    text(d,84,441,"action_control_contract {",30,BLUE,True,mono=True,width=907)
    for i,line in enumerate(p["contract"]):
        y=517+i*73
        active=t>i*.38+.4
        if active:
            d.line((99,y+20,106,y+27,119,y+10),fill=BLUE,width=3)
        else:
            d.ellipse((106,y+17,112,y+23),fill=BLUE)
        text(d,151,y,line,26,INK if active else BLUE,width=835,max_lines=1,mono=True)
    text(d,84,978,"}",30,BLUE,True,mono=True)
    scan_y=497+(t%3)/3*442
    d.line((80,scan_y,96,scan_y),fill=BLUE,width=4)
    text(d,54,1092,"Versioned inputs. Explicit scope. Reviewable evidence.",30,BLUE,True,width=960,max_lines=2)


def scene_failure(p,d,t):
    heading(d,"Test the failure path", "A safe terminal state is an observable result, not a reassuring answer.")
    labels=["INJECT","ENFORCE","RESOLVE"]
    active=min(2,int(t/1.55))
    for i,(label,body) in enumerate(zip(labels,p["failure"])):
        y=411+i*215
        box(d,(54,y,1026,y+168),PALE if active==i else WHITE,BLUE if active==i else LINE,3 if active==i else 2)
        text(d,82,y+26,label,22,BLUE,True)
        text(d,82,y+71,body,31,INK,True,width=902,max_lines=2)
        if i<2:arrow(d,(540,y+173),(540,y+210),t*.8,dashed=True)
    text(d,54,1092,"Reject, hold or recover—never silently skip the boundary.",30,BLUE,True,width=960,max_lines=2)


def scene_decision(p,d,t):
    heading(d,"Turn the design into an operating test",p["decision_rule"])
    for i,(label,value,state) in enumerate(p["score_rows"][-3:]):
        y=431+i*118
        box(d,(54,y,1026,y+93),PALE if int(t)%3==i else WHITE)
        text(d,77,y+30,label,25,INK,True,width=470,max_lines=1)
        text(d,560,y+23,value,33,BLUE,True,width=250,max_lines=1)
        text(d,830,y+34,state,17,INK,True,width=173,max_lines=1)
    text(d,54,850,"THE QUESTION TO TAKE INTO DESIGN REVIEW",21,BLUE,True)
    text(d,54,905,p["question"],46,INK,True,width=960,max_lines=3)
    text(d,54,1125,"Read the full context in the accompanying post.",27,BLUE,width=950)


SCENES=[scene_problem,scene_arch,scene_evidence,scene_contract,scene_failure,scene_decision]


def render(p,t):
    index=min(5,int(t//6)); local=t-index*6
    image,d=base(p,index,t)
    SCENES[index](p,d,local)
    # Smooth horizontal reveal at scene boundaries; the diagrams also animate
    # within every scene, so this is not a slideshow of still assets.
    if local<.32 and index>0:
        prior,pd=base(p,index-1,t)
        SCENES[index-1](p,pd,5.9)
        split=int(W*smooth(local/.32))
        prior.paste(image.crop((0,0,split,H)),(0,0))
        ImageDraw.Draw(prior).line((split,0,split,H),fill=BLUE,width=4)
        return prior
    return image


def storyboard(p,dest):
    board=Image.new("RGB",(1080,2025),WHITE)
    for i in range(6):
        frame=render(p,i*6+3.8).resize((540,675),Image.Resampling.LANCZOS)
        board.paste(frame,((i%2)*540,(i//2)*675))
    board.save(dest/"storyboard.png",optimize=True)


def encode(p,dest):
    output=dest/"motion.mp4"
    proc=subprocess.Popen(["ffmpeg","-y","-loglevel","error","-f","rawvideo","-pix_fmt","rgb24","-s",f"{W}x{H}","-r",str(FPS),"-i","-","-an","-c:v","libx264","-preset","fast","-crf","18","-pix_fmt","yuv420p","-movflags","+faststart",str(output)],stdin=subprocess.PIPE)
    assert proc.stdin
    for n in range(FPS*SECONDS):
        proc.stdin.write(render(p,n/FPS).tobytes())
    proc.stdin.close()
    if proc.wait():raise RuntimeError("MP4 encode failed")
    subprocess.run(["ffmpeg","-y","-loglevel","error","-i",str(output),"-filter_complex","[0:v]fps=10,scale=720:900:flags=lanczos,split[a][b];[a]palettegen=max_colors=96[p];[b][p]paletteuse=dither=bayer:bayer_scale=4","-loop","0",str(dest/"motion.gif")],check=True)
    render(p,2.4).save(dest/"poster.png",optimize=True)


def gallery(items):
    cards=[]
    for p in items:
        folder=p["id"].lower()+"-"+p["slug"]
        cards.append(f'<article id="{p["id"]}"><h2>{p["id"]} · {html.escape(p["title"])}</h2><p>{p["schedule"][:16].replace("T"," ")} IST · Currently: {p["media"]}</p><video controls playsinline preload="none" poster="{folder}/poster.png" src="{folder}/motion.mp4"></video><p><a href="{folder}/motion.gif">Looping GIF</a> · <a href="{folder}/motion.mp4">MP4</a> · <a href="{folder}/storyboard.png">Six-scene storyboard</a></p><details><summary>Motion transcript and source context</summary><p>{html.escape(p["note"])}</p><ol>'+''.join(f'<li>{html.escape(str(x))}</li>' for x in [p['title'],p['lanes'],p['chart_note'],p['contract'],p['failure'],p['question']])+'</ol></details></article>')
    page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>14 scheduled LinkedIn motion previews</title><style>body{margin:0;background:#fff;color:#071426;font:17px/1.5 system-ui}header,main{max-width:1200px;margin:auto;padding:30px}header{border-bottom:2px solid #075bda}h1{font-size:38px}a{color:#075bda}main{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:32px}article{padding-bottom:28px;border-bottom:1px solid #bdd3f0}h2{font-size:24px;min-height:72px}video{width:100%;max-height:700px;background:white}summary{cursor:pointer;color:#075bda}@media(max-width:720px){main{grid-template-columns:1fr}h1{font-size:30px}}</style><header><h1>Scheduled LinkedIn motion previews</h1><p>14 topic-specific animations · 36 seconds · six progressive scenes · white / ink / blue</p><p><strong>Preparation only. No LinkedIn post has been changed.</strong> Proposed MP4 additions/replacements preserve all scheduled copy, mentions, links, permissions and dates. GIF versions are included; their native feed behavior has not been assumed.</p><p>Metrics are explicitly illustrative or attributed—not telemetry. Each video has its own runtime contract and failure path.</p></header><main>'''+''.join(cards)+'</main></html>'
    (OUT/"index.html").write_text(page)


def validate(items):
    checks=[]
    for p in items:
        dest=OUT/(p["id"].lower()+"-"+p["slug"])
        probe=json.loads(subprocess.check_output(["ffprobe","-v","error","-show_streams","-show_format","-of","json",str(dest/"motion.mp4")]))
        v=next(s for s in probe["streams"] if s["codec_type"]=="video")
        assert (v["width"],v["height"],v["codec_name"],v["pix_fmt"])==(W,H,"h264","yuv420p")
        assert abs(float(probe["format"]["duration"])-SECONDS)<.1
        assert int(v["nb_frames"])==FPS*SECONDS
        gif=Image.open(dest/"motion.gif")
        assert gif.n_frames>=300 and gif.info.get("loop")==0
        # Confirm actual GIF frames differ within each scene, not only at cuts.
        unique=[]
        for scene in range(6):
            hashes=set()
            for n in (8,20,35,48):
                gif.seek(scene*60+n)
                # Exclude the timeline/header: visible diagram motion must pass.
                hashes.add(hashlib.sha256(gif.convert("RGB").crop((35,270,685,780)).tobytes()).hexdigest())
            assert len(hashes)>=2,(p["id"],scene,hashes)
            unique.append(len(hashes))
        checks.append(dict(id=p["id"],mp4Frames=int(v["nb_frames"]),gifFrames=gif.n_frames,seconds=SECONDS,uniqueIntraSceneSamples=unique,mp4Sha256=hashlib.sha256((dest/"motion.mp4").read_bytes()).hexdigest(),gifSha256=hashlib.sha256((dest/"motion.gif").read_bytes()).hexdigest(),mp4Bytes=(dest/"motion.mp4").stat().st_size,gifBytes=(dest/"motion.gif").stat().st_size))
    # Independent arithmetic checks of the major derived claims.
    n,k,z=95,88,1.959963984540054
    phat=k/n
    wilson=(phat+z*z/(2*n)-z*math.sqrt(phat*(1-phat)/n+z*z/(4*n*n)))/(1+z*z/n)
    assert round(wilson*100,1)==85.6
    assert math.isclose(sum(x[1] for x in EXTRAS[4][1]),.186)
    assert math.isclose(sum(x[1] for x in EXTRAS[9][1]),.9502)
    assert round(.9502/.837,3)==1.135
    assert 80*180000/8==1800000
    if OVERFLOWS:raise AssertionError(sorted(OVERFLOWS))
    (OUT/"qa.json").write_text(json.dumps(dict(status="automated_checks_passed_visual_review_required",posts=checks,overflowCount=len(OVERFLOWS),wilsonLower95=wilson,livePostsChanged=0),indent=2)+"\n")


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--ids",nargs="*")
    parser.add_argument("--storyboards-only",action="store_true")
    parser.add_argument("--validate-only",action="store_true")
    args=parser.parse_args()
    all_posts=posts()
    chosen=[p for p in all_posts if not args.ids or p["id"] in args.ids]
    OUT.mkdir(parents=True,exist_ok=True)
    (OUT/"manifest.json").write_text(json.dumps(dict(status="prepared_not_applied",reference="https://www.linkedin.com/feed/update/urn:li:activity:7501596302342922240/",preserve=["text","links","native_mentions","hashtags","audience","comments","scheduled_time"],posts=all_posts),indent=2)+"\n")
    if args.validate_only:
        validate(chosen)
        print("Validated",len(chosen),"motion packages",flush=True)
        return
    for p in chosen:
        dest=OUT/(p["id"].lower()+"-"+p["slug"])
        dest.mkdir(parents=True,exist_ok=True)
        storyboard(p,dest)
        if not args.storyboards_only:encode(p,dest)
        print("Rendered",p["id"],p["slug"],flush=True)
    gallery(all_posts)
    if OVERFLOWS:raise AssertionError(sorted(OVERFLOWS))
    if not args.storyboards_only:validate(chosen)


if __name__=="__main__":main()
